echo "./app/models/orchids_name.rb"; cp ../ned/app/models/orchids_name.rb ./app/models/orchids_name.rb
echo "./app/models/orchid.rb"; cp ../ned/app/models/orchid.rb ./app/models/orchid.rb
echo "./app/models/orchid/as_instance_creator.rb"; cp ../ned/app/models/orchid/as_instance_creator.rb ./app/models/orchid/as_instance_creator.rb
echo "./app/models/orchid/as_name_matcher.rb"; cp ../ned/app/models/orchid/as_name_matcher.rb ./app/models/orchid/as_name_matcher.rb
echo "./app/models/orchid/as_tree_placer.rb"; cp ../ned/app/models/orchid/as_tree_placer.rb ./app/models/orchid/as_tree_placer.rb
echo "./app/models/orchid/as_instance_creator.rb"; cp ../ned/app/models/orchid/as_instance_creator.rb ./app/models/orchid/as_instance_creator.rb
echo "./app/controllers/orchids_controller.rb"; cp ../ned/app/controllers/orchids_controller.rb ./app/controllers/orchids_controller.rb
echo "./app/controllers/orchids_names_controller.rb"; cp ../ned/app/controllers/orchids_names_controller.rb ./app/controllers/orchids_names_controller.rb
echo "./app/controllers/orchids_batch_controller.rb"; cp ../ned/app/controllers/orchids_batch_controller.rb ./app/controllers/orchids_batch_controller.rb
echo "./app/views/orchids/_form_for_synonym.html.erb"; cp ../ned/app/views/orchids/_form_for_synonym.html.erb ./app/views/orchids/_form_for_synonym.html.erb
echo "./app/views/orchids/_synonym_type.html.erb"; cp ../ned/app/views/orchids/_synonym_type.html.erb ./app/views/orchids/_synonym_type.html.erb
echo "./app/views/orchids/_tab_batch.html.erb"; cp ../ned/app/views/orchids/_tab_batch.html.erb ./app/views/orchids/_tab_batch.html.erb
echo "./app/views/orchids/_tab_show_1_name_matches_standard.html.erb"; cp ../ned/app/views/orchids/_tab_show_1_name_matches_standard.html.erb ./app/views/orchids/_tab_show_1_name_matches_standard.html.erb
echo "./app/views/orchids/_tab_show_standard_preferred_match_info.html.erb"; cp ../ned/app/views/orchids/_tab_show_standard_preferred_match_info.html.erb ./app/views/orchids/_tab_show_standard_preferred_match_info.html.erb
echo "./app/views/orchids/_form_for_synonym.html.erb"; cp ../ned/app/views/orchids/_form_for_synonym.html.erb ./app/views/orchids/_form_for_synonym.html.erb
echo "./app/views/orchids/_new_row.html.erb"; cp ../ned/app/views/orchids/_new_row.html.erb ./app/views/orchids/_new_row.html.erb
echo "./app/views/orchids/_synonym_type.html.erb"; cp ../ned/app/views/orchids/_synonym_type.html.erb ./app/views/orchids/_synonym_type.html.erb
echo "./app/views/orchids/_tab_show_1_name_matches_standard.html.erb"; cp ../ned/app/views/orchids/_tab_show_1_name_matches_standard.html.erb ./app/views/orchids/_tab_show_1_name_matches_standard.html.erb
echo "./app/views/orchids/_tab_batch.html.erb"; cp ../ned/app/views/orchids/_tab_batch.html.erb ./app/views/orchids/_tab_batch.html.erb
echo "./app/views/orchids_batch"; cp ../ned/app/views/orchids_batch ./app/views/orchids_batch
echo "./app/views/orchids_batch/create.js.erb"; cp ../ned/app/views/orchids_batch/create.js.erb ./app/views/orchids_batch/create.js.erb
echo "./app/views/application/_orchid_name_link_text.html.erb"; cp ../ned/app/views/application/_orchid_name_link_text.html.erb ./app/views/application/_orchid_name_link_text.html.erb
echo "./app/views/application/_orchid_record.html.erb"; cp ../ned/app/views/application/_orchid_record.html.erb ./app/views/application/_orchid_record.html.erb
