echo "./app/models/orchids_name.rb"; diff ../ned/app/models/orchids_name.rb ./app/models/orchids_name.rb
echo "./app/models/orchid.rb"; diff ../ned/app/models/orchid.rb ./app/models/orchid.rb
echo "./app/models/search/on_orchids"; diff ../ned/app/models/search/on_orchids ./app/models/search/on_orchids
echo "./app/models/search/on_orchids/base.rb"; diff ../ned/app/models/search/on_orchids/base.rb ./app/models/search/on_orchids/base.rb
echo "./app/models/search/on_orchids/list_query.rb"; diff ../ned/app/models/search/on_orchids/list_query.rb ./app/models/search/on_orchids/list_query.rb
echo "./app/models/search/on_orchids/where_clauses.rb"; diff ../ned/app/models/search/on_orchids/where_clauses.rb ./app/models/search/on_orchids/where_clauses.rb
echo "./app/models/search/on_orchids/predicate.rb"; diff ../ned/app/models/search/on_orchids/predicate.rb ./app/models/search/on_orchids/predicate.rb
echo "./app/models/search/on_orchids/field_abbrev.rb"; diff ../ned/app/models/search/on_orchids/field_abbrev.rb ./app/models/search/on_orchids/field_abbrev.rb
echo "./app/models/search/on_orchids/count_query.rb"; diff ../ned/app/models/search/on_orchids/count_query.rb ./app/models/search/on_orchids/count_query.rb
echo "./app/models/search/on_orchids/field_rule.rb"; diff ../ned/app/models/search/on_orchids/field_rule.rb ./app/models/search/on_orchids/field_rule.rb
echo "./app/models/orchid"; diff ../ned/app/models/orchid ./app/models/orchid
echo "./app/models/orchid/as_typeahead"; diff ../ned/app/models/orchid/as_typeahead ./app/models/orchid/as_typeahead
echo "./app/models/orchid/as_typeahead/for_parent.rb"; diff ../ned/app/models/orchid/as_typeahead/for_parent.rb ./app/models/orchid/as_typeahead/for_parent.rb
echo "./app/models/orchid/as_name_matcher.rb"; diff ../ned/app/models/orchid/as_name_matcher.rb ./app/models/orchid/as_name_matcher.rb
echo "./app/models/orchid/as_tree_placer.rb"; diff ../ned/app/models/orchid/as_tree_placer.rb ./app/models/orchid/as_tree_placer.rb
echo "./app/models/orchid/as_instance_creator.rb"; diff ../ned/app/models/orchid/as_instance_creator.rb ./app/models/orchid/as_instance_creator.rb
echo "./app/javascript/packs/typeaheads/for_orchids"; diff ../ned/app/javascript/packs/typeaheads/for_orchids ./app/javascript/packs/typeaheads/for_orchids
echo "./app/javascript/packs/typeaheads/for_orchids/parent.js"; diff ../ned/app/javascript/packs/typeaheads/for_orchids/parent.js ./app/javascript/packs/typeaheads/for_orchids/parent.js
echo "./app/controllers/orchids_controller.rb"; diff ../ned/app/controllers/orchids_controller.rb ./app/controllers/orchids_controller.rb
echo "./app/controllers/orchids_names_controller.rb"; diff ../ned/app/controllers/orchids_names_controller.rb ./app/controllers/orchids_names_controller.rb
echo "./app/controllers/orchids_batch_controller.rb"; diff ../ned/app/controllers/orchids_batch_controller.rb ./app/controllers/orchids_batch_controller.rb
echo "./app/views/orchids_names"; diff ../ned/app/views/orchids_names ./app/views/orchids_names
echo "./app/views/orchids_names/update_error.js.erb"; diff ../ned/app/views/orchids_names/update_error.js.erb ./app/views/orchids_names/update_error.js.erb
echo "./app/views/orchids_names/update.js.erb"; diff ../ned/app/views/orchids_names/update.js.erb ./app/views/orchids_names/update.js.erb
echo "./app/views/orchids_names/create.js.erb"; diff ../ned/app/views/orchids_names/create.js.erb ./app/views/orchids_names/create.js.erb
echo "./app/views/orchids"; diff ../ned/app/views/orchids ./app/views/orchids
echo "./app/views/orchids/_tab_show_standard_preferred_match_info.html.erb"; diff ../ned/app/views/orchids/_tab_show_standard_preferred_match_info.html.erb ./app/views/orchids/_tab_show_standard_preferred_match_info.html.erb
echo "./app/views/orchids/_delete_widgets.html.erb"; diff ../ned/app/views/orchids/_delete_widgets.html.erb ./app/views/orchids/_delete_widgets.html.erb
echo "./app/views/orchids/form"; diff ../ned/app/views/orchids/form ./app/views/orchids/form
echo "./app/views/orchids/form/_parent.html.erb"; diff ../ned/app/views/orchids/form/_parent.html.erb ./app/views/orchids/form/_parent.html.erb
echo "./app/views/orchids/stats.js.erb"; diff ../ned/app/views/orchids/stats.js.erb ./app/views/orchids/stats.js.erb
echo "./app/views/orchids/_form_for_synonym.html.erb"; diff ../ned/app/views/orchids/_form_for_synonym.html.erb ./app/views/orchids/_form_for_synonym.html.erb
echo "./app/views/orchids/_tab_delete.html.erb"; diff ../ned/app/views/orchids/_tab_delete.html.erb ./app/views/orchids/_tab_delete.html.erb
echo "./app/views/orchids/_new_row.html.erb"; diff ../ned/app/views/orchids/_new_row.html.erb ./app/views/orchids/_new_row.html.erb
echo "./app/views/orchids/_synonym_type.html.erb"; diff ../ned/app/views/orchids/_synonym_type.html.erb ./app/views/orchids/_synonym_type.html.erb
echo "./app/views/orchids/new_row.js.erb"; diff ../ned/app/views/orchids/new_row.js.erb ./app/views/orchids/new_row.js.erb
echo "./app/views/orchids/update_error.js.erb"; diff ../ned/app/views/orchids/update_error.js.erb ./app/views/orchids/update_error.js.erb
echo "./app/views/orchids/new.js.erb"; diff ../ned/app/views/orchids/new.js.erb ./app/views/orchids/new.js.erb
echo "./app/views/orchids/destroy.js.erb"; diff ../ned/app/views/orchids/destroy.js.erb ./app/views/orchids/destroy.js.erb
echo "./app/views/orchids/update_no_change.js.erb"; diff ../ned/app/views/orchids/update_no_change.js.erb ./app/views/orchids/update_no_change.js.erb
echo "./app/views/orchids/create_error.js.erb"; diff ../ned/app/views/orchids/create_error.js.erb ./app/views/orchids/create_error.js.erb
echo "./app/views/orchids/_tabs.html.erb"; diff ../ned/app/views/orchids/_tabs.html.erb ./app/views/orchids/_tabs.html.erb
echo "./app/views/orchids/_tab_create_misapp.html.erb"; diff ../ned/app/views/orchids/_tab_create_misapp.html.erb ./app/views/orchids/_tab_create_misapp.html.erb
echo "./app/views/orchids/_form_for_accepted.html.erb"; diff ../ned/app/views/orchids/_form_for_accepted.html.erb ./app/views/orchids/_form_for_accepted.html.erb
echo "./app/views/orchids/_new.html.erb"; diff ../ned/app/views/orchids/_new.html.erb ./app/views/orchids/_new.html.erb
echo "./app/views/orchids/_tab_show_1_name_matches_standard.html.erb"; diff ../ned/app/views/orchids/_tab_show_1_name_matches_standard.html.erb ./app/views/orchids/_tab_show_1_name_matches_standard.html.erb
echo "./app/views/orchids/update.js.erb"; diff ../ned/app/views/orchids/update.js.erb ./app/views/orchids/update.js.erb
echo "./app/views/orchids/_tab_show_1_more_info.html.erb"; diff ../ned/app/views/orchids/_tab_show_1_more_info.html.erb ./app/views/orchids/_tab_show_1_more_info.html.erb
echo "./app/views/orchids/_tab_show_1_name_matches_misapplied.html.erb"; diff ../ned/app/views/orchids/_tab_show_1_name_matches_misapplied.html.erb ./app/views/orchids/_tab_show_1_name_matches_misapplied.html.erb
echo "./app/views/orchids/_form_for_hybrid_cross.html.erb"; diff ../ned/app/views/orchids/_form_for_hybrid_cross.html.erb ./app/views/orchids/_form_for_hybrid_cross.html.erb
echo "./app/views/orchids/_tab.html.erb"; diff ../ned/app/views/orchids/_tab.html.erb ./app/views/orchids/_tab.html.erb
echo "./app/views/orchids/create.js.erb"; diff ../ned/app/views/orchids/create.js.erb ./app/views/orchids/create.js.erb
echo "./app/views/orchids/_tab_chosen.html.erb"; diff ../ned/app/views/orchids/_tab_chosen.html.erb ./app/views/orchids/_tab_chosen.html.erb
echo "./app/views/orchids/destroy_error.js.erb"; diff ../ned/app/views/orchids/destroy_error.js.erb ./app/views/orchids/destroy_error.js.erb
echo "./app/views/orchids/show.html.erb"; diff ../ned/app/views/orchids/show.html.erb ./app/views/orchids/show.html.erb
echo "./app/views/orchids/_tab_show_1.html.erb"; diff ../ned/app/views/orchids/_tab_show_1.html.erb ./app/views/orchids/_tab_show_1.html.erb
echo "./app/views/orchids/_tab_create_syn.html.erb"; diff ../ned/app/views/orchids/_tab_create_syn.html.erb ./app/views/orchids/_tab_create_syn.html.erb
echo "./app/views/orchids/_ex_base_author.html.erb"; diff ../ned/app/views/orchids/_ex_base_author.html.erb ./app/views/orchids/_ex_base_author.html.erb
echo "./app/views/orchids/_form_for_misapp.html.erb"; diff ../ned/app/views/orchids/_form_for_misapp.html.erb ./app/views/orchids/_form_for_misapp.html.erb
echo "./app/views/orchids/_tab_show_1_name_matches.html.erb"; diff ../ned/app/views/orchids/_tab_show_1_name_matches.html.erb ./app/views/orchids/_tab_show_1_name_matches.html.erb
echo "./app/views/orchids/_authors.html.erb"; diff ../ned/app/views/orchids/_authors.html.erb ./app/views/orchids/_authors.html.erb
echo "./app/views/orchids/_tab_show_1_core_info.html.erb"; diff ../ned/app/views/orchids/_tab_show_1_core_info.html.erb ./app/views/orchids/_tab_show_1_core_info.html.erb
echo "./app/views/orchids/_name_status.html.erb"; diff ../ned/app/views/orchids/_name_status.html.erb ./app/views/orchids/_name_status.html.erb
echo "./app/views/orchids/stats"; diff ../ned/app/views/orchids/stats ./app/views/orchids/stats
echo "./app/views/orchids/stats/_nsl_rank_really_excluded_stats.html.erb"; diff ../ned/app/views/orchids/stats/_nsl_rank_really_excluded_stats.html.erb ./app/views/orchids/stats/_nsl_rank_really_excluded_stats.html.erb
echo "./app/views/orchids/stats/_nsl_rank_accepted_stats.html.erb"; diff ../ned/app/views/orchids/stats/_nsl_rank_accepted_stats.html.erb ./app/views/orchids/stats/_nsl_rank_accepted_stats.html.erb
echo "./app/views/orchids/stats/_ranks_by_record_type.html.erb"; diff ../ned/app/views/orchids/stats/_ranks_by_record_type.html.erb ./app/views/orchids/stats/_ranks_by_record_type.html.erb
echo "./app/views/orchids/stats/_high_level_stats.html.erb"; diff ../ned/app/views/orchids/stats/_high_level_stats.html.erb ./app/views/orchids/stats/_high_level_stats.html.erb
echo "./app/views/orchids/stats/_nsl_rank_synonym_stats.html.erb"; diff ../ned/app/views/orchids/stats/_nsl_rank_synonym_stats.html.erb ./app/views/orchids/stats/_nsl_rank_synonym_stats.html.erb
echo "./app/views/orchids/stats/_rank_stats.html.erb"; diff ../ned/app/views/orchids/stats/_rank_stats.html.erb ./app/views/orchids/stats/_rank_stats.html.erb
echo "./app/views/orchids/stats/_nsl_rank_stats.html.erb"; diff ../ned/app/views/orchids/stats/_nsl_rank_stats.html.erb ./app/views/orchids/stats/_nsl_rank_stats.html.erb
echo "./app/views/orchids/stats/_nsl_rank_misapps_stats.html.erb"; diff ../ned/app/views/orchids/stats/_nsl_rank_misapps_stats.html.erb ./app/views/orchids/stats/_nsl_rank_misapps_stats.html.erb
echo "./app/views/orchids/stats/_name_status.html.erb"; diff ../ned/app/views/orchids/stats/_name_status.html.erb ./app/views/orchids/stats/_name_status.html.erb
echo "./app/views/orchids/stats/_nsl_rank_really_accepted_stats.html.erb"; diff ../ned/app/views/orchids/stats/_nsl_rank_really_accepted_stats.html.erb ./app/views/orchids/stats/_nsl_rank_really_accepted_stats.html.erb
echo "./app/views/orchids/stats/_nsl_rank_hybrid_cross_stats.html.erb"; diff ../ned/app/views/orchids/stats/_nsl_rank_hybrid_cross_stats.html.erb ./app/views/orchids/stats/_nsl_rank_hybrid_cross_stats.html.erb
echo "./app/views/orchids/advanced_search"; diff ../ned/app/views/orchids/advanced_search ./app/views/orchids/advanced_search
echo "./app/views/orchids/advanced_search/_field_help.html.erb"; diff ../ned/app/views/orchids/advanced_search/_field_help.html.erb ./app/views/orchids/advanced_search/_field_help.html.erb
echo "./app/views/orchids/advanced_search/_examples.html.erb"; diff ../ned/app/views/orchids/advanced_search/_examples.html.erb ./app/views/orchids/advanced_search/_examples.html.erb
echo "./app/views/orchids/advanced_search/_help.html.erb"; diff ../ned/app/views/orchids/advanced_search/_help.html.erb ./app/views/orchids/advanced_search/_help.html.erb
echo "./app/views/orchids/_tab_edit.html.erb"; diff ../ned/app/views/orchids/_tab_edit.html.erb ./app/views/orchids/_tab_edit.html.erb
echo "./app/views/orchids/_tab_batch.html.erb"; diff ../ned/app/views/orchids/_tab_batch.html.erb ./app/views/orchids/_tab_batch.html.erb
echo "./app/views/orchids_batch"; diff ../ned/app/views/orchids_batch ./app/views/orchids_batch
echo "./app/views/orchids_batch/error.js.erb"; diff ../ned/app/views/orchids_batch/error.js.erb ./app/views/orchids_batch/error.js.erb
echo "./app/views/orchids_batch/create.js.erb"; diff ../ned/app/views/orchids_batch/create.js.erb ./app/views/orchids_batch/create.js.erb
echo "./app/views/application/_orchid_name_link_text.html.erb"; diff ../ned/app/views/application/_orchid_name_link_text.html.erb ./app/views/application/_orchid_name_link_text.html.erb
echo "./app/views/application/_orchid_record.html.erb"; diff ../ned/app/views/application/_orchid_record.html.erb ./app/views/application/_orchid_record.html.erb
