// Generated by CoffeeScript 2.6.1
(function() {
  var debug, debugObject;

  debug = function(s) {
    var error;
    try {
      if (debugSwitch === true) {
        return console.log('debug: ' + s);
      }
    } catch (error1) {
      error = error1;
    }
  };

  window.debug = debug;

  window.notice = function(s) {
    var error;
    try {
      return console.log('notice: ' + s);
    } catch (error1) {
      error = error1;
    }
  };

  debugObject = function(obj) {
    debug('show object');
    $.each(obj, function(key, element) {
      if (element) {
        return debug("key: " + key + "\n" + "value: " + element);
      }
    });
  };

}).call(this);
