// Generated by CoffeeScript 2.6.1
(function() {
  var currentActiveTab, recordCurrentActiveTab, reviewResultKeyNavigation, searchResultKeyNavigation;

  $(document).on("turbo:load", function() {
    debug('Start of keyboard_nav.js turbo loaded');

    $('tr.search-result').keydown(function(event) {
      return searchResultKeyNavigation(event, $(this));
    });

    $('tr.review-result').keydown(function(event) {
      return reviewResultKeyNavigation(event, $(this));
    });

  });


  currentActiveTab = function(record_type) {
    debug("state of " + record_type + ` tab: ${$('body').attr('data-active-' + record_type + '-tab')} via currentActiveTab`);
    return $('body').attr('data-active-' + record_type + '-tab');
  };

  recordCurrentActiveTab = function(record_type) {
    return $('body').attr('data-active-' + record_type + '-tab', $('div#search-result-details ul.nav-tabs li.active a').attr('data-tab-name'));
  };

  searchResultKeyNavigation = function(event, $this) {
    var arrowDown, arrowLeft, arrowRight, arrowUp, keep_going;
    debug('searchResultKeyNavigation start');
    arrowLeft = 37;
    arrowRight = 39;
    arrowUp = 38;
    arrowDown = 40;
    keep_going = false;
    switch (event.keyCode) {
      case arrowLeft:
        moveToSearchResultDetails($this, 'last');
        break;
      case arrowRight:
        moveToSearchResultDetails($this, 'first');
        break;
      case arrowUp:
        moveUpOneSearchResult($this);
        break;
      case arrowDown:
        moveDownOneSearchResult($this);
        break;
      default:
        keep_going = true;
    }
    if (!keep_going) {
      return event.preventDefault();
    }
  };
  window.searchResultKeyNavigation = searchResultKeyNavigation;

  reviewResultKeyNavigation = function(event, $this) {
    var arrowDown, arrowLeft, arrowRight, arrowUp, keep_going;
    debug('reviewResultKeyNavigation ');
    arrowLeft = 37;
    arrowRight = 39;
    arrowUp = 38;
    arrowDown = 40;
    keep_going = false;
    switch (event.keyCode) {
      case arrowLeft:
        moveToSearchResultDetails($this, 'last');
        break;
      case arrowRight:
        moveToSearchResultDetails($this, 'first');
        break;
      case arrowUp:
        moveUpOneReviewResult($this);
        break;
      case arrowDown:
        moveDownOneReviewResult($this);
        break;
      default:
        keep_going = true;
    }
    if (!keep_going) {
      return event.preventDefault();
    }
  };

  window.moveUpOneSearchResult = function(startRow) {
    return startRow.prev().find('a.show-details-link').focus();
  };

  window.moveDownOneSearchResult = function(startRow) {
    return startRow.next().find('a.show-details-link').focus();
  }

  window.moveUpOneReviewResult = function(row) {
    if (row.prev()) {
      if (row.prev().find('a.navigation-link').length === 1) {
        return row.prev().find('a.navigation-link').focus();
      } else {
        // skip white-space boundary row
        return row.prev().prev().find('a.navigation-link').focus();
      }
    }
  };

  window.moveDownOneReviewResult = function(row) {
    if (row.next().find('a.navigation-link').length === 1) {
      return row.next().find('a.navigation-link').focus();
    } else {
      // skip white-space boundary row
      return row.next().next().find('a.navigation-link').focus();
    }
  };

  window.moveToSearchResultDetails = function(searchResultDetail, liElementHasClass) {
    return $('#search-result-details ul li.' + liElementHasClass + ' a').focus();
  };

}).call(this);
