\i aa-create-table-loader-batch-raw-names-for-date.sql
\i b-load-raw-data.sql
\i c-insert-batch.sql
\i d-copy-raw-to-loader-name.sql
\i e-bulk-update-loader-name-parent-id.sql
\i f-clean-tags-out-of-remark-to-reviewers.sal
\i g-replace-multiplication-signs.sql
\i h-set-long-dash-to-dash.sql
\i i-translate-synonym-types.sql
\i j-remove-trailing-white-simple-name.sql 
\i k-remove-trailing-white-full-name.sql 
\i l-set-record-type-excluded.sql
\i m-update-family-records-to-headings.sql
