create table loader_name
 (id bigint default nextval('nsl_global_seq'::regclass) primary key,
  loader_batch_id bigint not null,
  raw_id int, 
  parent_raw_id int,
  parent_id bigint,
  record_type text not null,
  hybrid text,
  family text not null,
  higher_rank_comment text,
  subfamily text,
  tribe text,
  subtribe text,
  rank text,
  rank_nsl text,
  scientific_name text not null default 'not-supplied-on-load',
  ex_base_author text,
  base_author text,
  ex_author text,
  author text,
  author_rank text,
  name_status text,
  name_comment text,
  partly text,
  auct_non text,
  unplaced text,
  synonym_type text,
  doubtful text,
  hybrid_flag text,
  isonym text,
  publ_count bigint,
  article_author text,
  article_title text,
  article_title_full text,
  in_flag text,
  second_author text,
  title text,
  title_full text,
  edition text,
  volume text,
  page text,
  year text,
  date_ text,
  publ_partly text,
  publ_note text,
  notes text,
  footnote text,
  distribution text,
  comment text,
  remark text,
  original_text text,
  seq bigint not null default 0,
  alt_name_for_matching text,
  no_further_processing boolean not null default false,
  excluded boolean not null default false,
  reviewer_notice text,
  lock_version bigint not null default 0,
  updated_at timestamp with time zone not null default Now(),
  updated_by varchar(255) not null default 'batch',
  created_at timestamp with time zone not null default Now(),
  created_by varchar(255) not null default 'batch',
  constraint loader_name_loader_batch_id_fk foreign key (loader_batch_id) REFERENCES loader_batch(id),
  constraint loader_name_parent_id_fk foreign key (parent_id) REFERENCES loader_name(id)
  );

