\i create-table-users.sql
\i create-table-org.sql
\i create-table-batch-review-role.sql
\i create-table-batch-review.sql
\i create-table-batch-review-period.sql
\i create-table-batch-reviewer.sql
\i create-table-batch-review-comment.sql
\i ../nsl-4078/create-table-name-review-comment-type.sql
\i create-table-name-review-comment.sql
\i create-table-loader-name-match.sql
