insert into org (name,abbrev) values ('Tasmanian Museum and Art Gallery','TASMAG');
insert into org (name,abbrev) values ('Centre for Australian National Biodiversity Research - Australian National Herbarium','CANBR-ANH');
insert into org (name,abbrev) values ('Queensland Herbarium','QH');
insert into org (name,abbrev) values ('Royal Botanic Gardens Victoria','RBGV');
insert into org (name,abbrev) values ('Northern Territory Government','NTGov');
insert into org (name,abbrev) values ('Macquarie University','MacqUni');
insert into org (name,abbrev) values ('The Royal Botanic Garden Sydney','RBGSyd');
insert into org (name,abbrev) values ('Western Australian Herbarium','WAHerb');
insert into org (name,abbrev) values ('Australian Tropical Herbarium','ATH');
insert into org (name,abbrev, no_org) values ('No Organisation - Unaffiliated','NONE', true);
